services:
  redis-machine-a-one:
    container_name: "redis-machine-a-one"
    image: redis
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/one:/data/"
      - "./master.conf:/etc/redis.conf"
    networks:
      - redis-test-net

  redis-machine-a-two:
    container_name: "redis-machine-a-two"
    image: redis
    ports:
      - "6380:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./data/two:/data/"
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-machine-a-one
    networks:
      - redis-test-net

  redis-machine-a-sentinel:
    container_name: 'redis-machine-a-sentinel'
    image: redis
    ports:
      - "26379:26379"
    command: "redis-server /etc/sentinel.conf --sentinel"
    volumes:
      - "./sentinel.conf:/etc/sentinel.conf"
    depends_on:
      - redis-machine-a-one
      - redis-machine-a-two
    networks:
      - redis-test-net


networks:
  redis-test-net:
    external: true